# baseURL = "https://m4rr.ru/"
baseURL = "http://localhost/"
languageCode = "en-us"
title = "Marat Saytakov"

metaDataFormat = "yaml"
defaultContentLanguage = "en"
# SectionPagesMenu = "main"
# Paginate = 10
enableRobotsTXT = true
# summaryLength = 50
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS"]

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  description = "iOS Developer && Traveler"
  images = ["m4rr.ru-og-image.png"]
  title = "Marat Saytakov"

  # favicon = ""
  custom_scss = ["welcome.scss"]
  custom_js = ["js/amaps.js", "js/helpers.js"]

  countries = 32
  cities = 256
