baseURL = "https://m4rr.ru/"
languageCode = "en-us"
title = "Marat Say"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
# SectionPagesMenu = "main"
# Paginate = 10
enableRobotsTXT = true
# summaryLength = 50

# [sitemap]
#   changefreq = "weekly"
#   priority = 0.5
#   filename = "sitemap.xml"

[params]
  description = "iOS Developer && Traveler"
  images = ["m4rr.ru-og-image.png"]
  title = "Marat Saytakov"

  # favicon = ""
  custom_scss = ["welcome.scss"]
  custom_js = ["js/gmap3.min.js", "js/map.js", "js/helpers.js"]

  countries = 32
  cities = 256
