version: "3.7"
services:

  m4rr_ru_static:
    build: .
    restart: always
    labels: 
      - traefik.enable=true
      
      # - traefik.http.routers.m4rr-ru.entrypoints=http
      - traefik.http.routers.m4rr-ru.rule=Host(`m4rr.ru`,`saytakov.com`)
    networks: 
      - traefik
    # ports:
      # - "3000:80"
    # environment: # &environment
      # - VIRTUAL_HOST=m4rr.ru,saytakov.com
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs:/var/log/nginx:rw
      # - ./public:/usr/share/nginx/html:ro

  traefik:
    image: traefik:chevrotin
    restart: always
    command: 
      - -entrypoints.http.address=:80

      - -providers.docker=true
      - -providers.docker.exposedbydefault=false

      - -accesslog=true
      - -accesslog.filepath=/var/log/traefik/access.log
    labels: 
      - traefik.enable=true
    volumes: 
      - ./data/traefik:/var/log/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks: 
      - traefik
    ports: 
      - 80:80

networks: 
  traefik:
    external: 
      name: traefik
