version: "3"
services:
  static_files:
    build: .
    restart: unless-stopped
    ports:
      - "3000:80"
      - "4000:8080"
    environment: # &environment
      - VIRTUAL_HOST=m4rr.ru,saytakov.com
