version: "3"
services:
  static_files:
    build: .
    # command: bash -c "bundle exec puma -C ./config/puma.rb config.ru"
    restart: unless-stopped
    # volumes:
    #   - railsocket:/tmp/
    #   - .:/myapp
    ports:
      - "3000:3000"
    container_name: static_files
    environment: &environment
      - VIRTUAL_HOST=m4rr.ru
